"""
    This is the main project build system
"""

import sys

platform = sys.platform

print(platform)

env = Environment(
    TARGET_ARCH='x86',
    CPPPATH=[
        "#/include"
    ],
    LIBPATH=[
        "#/lib",
        "#/bin"
    ],
    LIBS=[
        'SDL3.lib',
        'SDL3_image.lib',
        'opengl32.lib',
        'glew32.lib',
        'assimp-vc141-mt.lib',
        'jsoncpp.lib',
        'lua.lib',
        'LinearMath.lib',
        'BulletCollision.lib',
        'BulletDynamics.lib',
        'vorbis.lib',
        'vorbisenc.lib',
        'vorbisfile.lib',
        'ogg.lib',
        'OpenAL32.lib',
        'engine.lib',
        'kernel32.lib',
        'user32.lib',
        'gdi32.lib',
        'winspool.lib',
        'comdlg32.lib',
        'advapi32.lib' ,
        'shell32.lib',
        'ole32.lib',
        'oleaut32.lib',
        'uuid.lib',
        'odbc32.lib',
        'odbccp32.lib'
    ],
    CPPFLAGS=[
        '/std:c++17',
        '/Gd',
        '/EHsc',
        '/fp:precise',
        '/MT',
        '/sdl',
    ],
    LINKFLAGS=[
        '/SUBSYSTEM:CONSOLE',
        '/MACHINE:X86',
        '/NODEFAULTLIB:library'])


if not (env is None):
    env["source_files"] = []

    target="#/bin/run"

    # Add in SConscripts
    SConscript("#/src/game/src/SConscript", exports="env")

    env.Program(target=target, source=env["source_files"])