Import("env")


def source(file):
    return "#/src/engine/src/script/" + file

env["source_files"] += []
"""
env["source_files"] += [
    source("app.cpp"),
    source("behavior.cpp"),
    source("component.cpp"),
    source("component_camera.cpp"),
    source("component_mesh.cpp"),
    source("component_body.cpp"),
    source("component_static_body.cpp"),
    source("component_dynamic_body.cpp"),
    source("component_kinematic_body.cpp"),
    source("component_trigger.cpp"),
    source("component_push_arm.cpp"),
    source("component_raycast.cpp"),
    source("component_sound_player.cpp"),
    source("entity.cpp"),
    source("global.cpp"),
    source("input.cpp"),
    source("input_mapping.cpp"),
    source("physics.cpp"),
    source("manager.cpp"),
    source("scene.cpp"),
    source("script.cpp"),
    source("sound.cpp"),
    source("transform.cpp"),
    source("util_random.cpp")
]
"""