Import("env")


def source(file):
    return "#/src/engine/src/script/" + file

env["source_files"] += [
    source("app.cpp"),
    source("behavior.cpp"),
    source("component_CameraComponent.cpp"),
    source("component_MeshComponent.cpp"),
    source("component_StaticBodyComponent.cpp"),
    source("component_DynamicBodyComponent.cpp"),
    source("entity.cpp"),
    source("global.cpp"),
    source("input.cpp"),
    source("input_mapping.cpp"),
    source("physics.cpp"),
    source("manager.cpp"),
    source("scene.cpp"),
    source("script.cpp"),
    source("transform.cpp"),
    source("util_random.cpp")
]