Import("env")


def source(file):
    return "#/src/engine/src/" + file

env["source_files"] += [
    source("app.cpp"),
    source("assets.cpp")
]

# SConscript("#/src/engine/src/SConscript", exports="env")
# input
SConscript("#/src/engine/src/input/SConscript", exports="env")
# manager
SConscript("#/src/engine/src/manager/SConscript", exports="env")
# render
SConscript("#/src/engine/src/render/SConscript", exports="env")
# script
SConscript("#/src/engine/src/script/SConscript", exports="env")
# util
SConscript("#/src/engine/src/util/SConscript", exports="env")