Import("env")


def source(file):
    return "#/src/engine/src/manager/" + file

env["source_files"] += [
    source("manager.cpp"),
    source("behavior.cpp"),
    source("component.cpp"),
    source("component_render.cpp"),
    source("component_physics.cpp"),
    source("component_sound.cpp"),
    source("entity.cpp"),
    source("global.cpp"),
    source("scene.cpp"),
    source("transform.cpp")
]
