Import("env")


def source(file):
    return "#/src/engine/src/render/" + file

env["source_files"] += [
    source("glw.cpp"),
    source("material.cpp"),
    source("mesh.cpp"),
    source("render.cpp")
]